# -*- mode: ruby -*-
# vi: set ft=ruby :


# -------------------------------------------
# set your project name here. bootstrap.sh will get it
# -------------------------------------------
$projectName = "ox_project"


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Ubuntu 12.04 LTS 64 bits
  config.vm.box = "hashicorp/precise64"

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # Recommended: Do not share OxCart and OxCMS from your local file system, rather, use svn subrepositories in your project.

  # Default to the project directory.
  config.vm.synced_folder "..", "/home/project/" + $projectName
  
  # Framework directory.
  config.vm.synced_folder "../../ox", "/home/project/ox"

  #HTTP
  config.vm.network :forwarded_port, guest: 80, host: 8080
  #HTTPS
  config.vm.network :forwarded_port, guest: 443, host: 8443

  config.vm.network :forwarded_port, guest: 27017, host: 8017 # mongod/mongos
  #config.vm.network :forwarded_port, guest: 27018, host: 8018 # shard server
  config.vm.network :forwarded_port, guest: 27019, host: 8019 # config server
  config.vm.network :forwarded_port, guest: 28017, host: 8081 # web status page

  config.vm.provision :shell, :path => "bootstrap.sh", :args => $projectName
end
