FROM registry.gitlab.com/lunar-logic/docker/apache-php/prod:v0.0.0

MAINTAINER Lunar Logic <support@lunarlogic.com>

WORKDIR /home/app/current

COPY Docker/php.ini /etc/php/5.6/apache2/php.ini
COPY Docker/bootstrap.sh bootstrap.sh

RUN chmod +x ./bootstrap.sh
RUN ./bootstrap.sh

COPY ./app-blank .
COPY ./ox ./ox

RUN chown -R www-data:www-data ..

ENTRYPOINT service apache2 start && /bin/bash
